# Generated by Django 3.2.9 on 2021-11-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
